<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.backup_type_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 225
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.Business_contact_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 253
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.location_id_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 280
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.application_info_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 308
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.ITcontact_person_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 168
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.ITcontact_team_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 140
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.Location_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 84
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.Inventory_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 57
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.Environment_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 113
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

<Exception>
<DateTime>6/1/2022 3:25:57 PM</DateTime>
<SessionID>gvorccuwifdzwkkmtr4lvhqi</SessionID>
<Summary>An unhandled exception occured on Wednesday, June 1, 2022 3:25:57 PM</Summary>
<Info>
<Verb>GET</Verb>
<URL>localhost/CreateInventoryForm.aspx</URL>
<HostIP>::1</HostIP>
</Info>
<Browser>
<Name>Chrome</Name>
<Version>102.0</Version>
<CookieSupport>True</CookieSupport>
<JSSupport>True</JSSupport>
<Platform>WinNT</Platform>
</Browser>
<User>Guest</User>
<ErrorMessage>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DBAWebsite.CreateInventory.sox_complaint_dropdownlist_DataBinding() in C:\DBA_WEB Backup\DBAWeb\DBAWebsite\CreateInventoryForm.aspx.cs:line 197
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20</ErrorMessage>
<InnerException>System.ComponentModel.Win32Exception (0x80004005): The network path was not found</InnerException>

</Exception>

